=== CruxFramework/crux/Crux/xsd/crux.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
	<!-- Element Definitions -->
	<xs:element name="crux" type="cruxT">
		<xs:annotation>
			<xs:documentation>Element Root for Crux Configuration File</xs:documentation>
		</xs:annotation>
	</xs:element>
	
	<xs:element name="component" type="componentT">
		<xs:annotation>
			<xs:documentation>Information for component registration in crux framework</xs:documentation>
		</xs:annotation>
	</xs:element>

	<!-- Type Definitions -->
	<xs:complexType name="cruxT">
		<xs:choice maxOccurs="unbounded" minOccurs="1">
			<xs:element ref="component"/>
		</xs:choice>
		<xs:attribute name="module" type="xs:string" use="required"/>		
	</xs:complexType>

	<xs:complexType name="componentT">
		<xs:attribute name="clientClass" type="xs:string" default="br.com.sysmap.crux.core.client.component.Component"/>		
		<xs:attribute name="clientConstructorParams" type="xs:string" default=" "/>		
		<xs:attribute name="id" type="xs:string" use="required"/>		
		<xs:attribute name="serverClass" type="xs:string" default="br.com.sysmap.crux.core.server.screen.Component"/>		
		<xs:attribute name="serverParserClass" type="xs:string" default="br.com.sysmap.crux.core.server.screen.ComponentParserImpl"/>		
		<xs:attribute name="parserInput" type="parserType" default="jericho"/>		
	</xs:complexType>

	<xs:simpleType name="parserType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="dom" />
			<xs:enumeration value="jericho" />
			<xs:enumeration value="string" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== CruxFramework/crux/Crux/src/crux.xml
<?xml version="1.0" encoding="UTF-8"?>
<crux xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xsi:noNamespaceSchemaLocation="../../Crux/xsd/crux.xsd"
      module="br.com.sysmap.crux.core.JSEngine">
  <component id="button" clientConstructorParams="id, new com.google.gwt.user.client.ui.Button()" />
  <component id="label" clientConstructorParams="id, new com.google.gwt.user.client.ui.Label()"/>
  <component id="textBox" clientConstructorParams="id, new com.google.gwt.user.client.ui.TextBox()"/>
  <component id="passwordTextBox" clientConstructorParams="id, new com.google.gwt.user.client.ui.PasswordTextBox()"/>
  
  
  <component id="simplePanel" 
  			 clientClass="br.com.sysmap.crux.core.client.component.Container"
             clientConstructorParams="id, new com.google.gwt.user.client.ui.SimplePanel()" 
             serverClass="br.com.sysmap.crux.core.server.screen.Container" />
  <component id="scrollPanel" 
  			 clientClass="br.com.sysmap.crux.core.client.component.Container"
             clientConstructorParams="id, new com.google.gwt.user.client.ui.ScrollPanel()"
             serverClass="br.com.sysmap.crux.core.server.screen.Container" />
  <component id="absolutePanel" 
  			 clientClass="br.com.sysmap.crux.core.client.component.Container"
             clientConstructorParams="id, new com.google.gwt.user.client.ui.AbsolutePanel()"
             serverClass="br.com.sysmap.crux.core.server.screen.Container" />
  <component id="stackPanel" 
  			 clientClass="br.com.sysmap.crux.core.client.component.Container"
             clientConstructorParams="id, new com.google.gwt.user.client.ui.StackPanel()"
             serverClass="br.com.sysmap.crux.core.server.screen.Container" />
             
             
</crux>

=== CruxFramework/crux/CruxBasicComponents/src/crux.xml
<?xml version="1.0" encoding="UTF-8"?>
<crux xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xsi:noNamespaceSchemaLocation="../../Crux/xsd/crux.xsd"
      module="br.com.sysmap.crux.ext.CruxBasicComponents">
  <component id="anchor" clientClass="br.com.sysmap.crux.basic.client.Anchor" />
  <component id="button" clientClass="br.com.sysmap.crux.basic.client.Button" />
  <component id="checkBox" clientClass="br.com.sysmap.crux.basic.client.CheckBox" />
  <component id="radioButton" clientClass="br.com.sysmap.crux.basic.client.RadioButton" />
  <component id="toggleButton" clientClass="br.com.sysmap.crux.basic.client.ToggleButton" />
  <component id="pushButton" clientClass="br.com.sysmap.crux.basic.client.PushButton" />
  <component id="listBox" clientClass="br.com.sysmap.crux.basic.client.ListBox" />
  <component id="richTextArea" clientClass="br.com.sysmap.crux.basic.client.RichTextArea" />
  <component id="simpleCheckBox" clientClass="br.com.sysmap.crux.basic.client.SimpleCheckBox" />
  <component id="simpleRadioButton" clientClass="br.com.sysmap.crux.basic.client.SimpleRadioButton" />
  <component id="textBox" clientClass="br.com.sysmap.crux.basic.client.TextBox" />
  <component id="textArea" clientClass="br.com.sysmap.crux.basic.client.TextArea" />
  <component id="passwordTextBox" clientClass="br.com.sysmap.crux.basic.client.PasswordTextBox"/>
  <component id="fileUpload" clientClass="br.com.sysmap.crux.basic.client.FileUpload"/>
  <component id="frame" clientClass="br.com.sysmap.crux.basic.client.Frame"/>
  <component id="namedFrame" clientClass="br.com.sysmap.crux.basic.client.NamedFrame" clientConstructorParams="id, element"/>
  <component id="hidden" clientClass="br.com.sysmap.crux.basic.client.Hidden"/>
  <component id="hyperlink" clientClass="br.com.sysmap.crux.basic.client.Hyperlink"/>
  <component id="inlineHyperlink" clientClass="br.com.sysmap.crux.basic.client.InlineHyperlink"/>
  <component id="image" clientClass="br.com.sysmap.crux.basic.client.Image"/>
  <component id="label" clientClass="br.com.sysmap.crux.basic.client.Label"/>
  <component id="html" clientClass="br.com.sysmap.crux.basic.client.HTML"/>
  <component id="inlineLabel" clientClass="br.com.sysmap.crux.basic.client.InlineLabel"/>
  <component id="inlineHtml" clientClass="br.com.sysmap.crux.basic.client.InlineHTML"/>
  <component id="menuBar" clientClass="br.com.sysmap.crux.basic.client.MenuBar" clientConstructorParams="id, element"/>
  <component id="tree" clientClass="br.com.sysmap.crux.basic.client.Tree" clientConstructorParams="id, element"/>
  <component id="simplePanel" clientClass="br.com.sysmap.crux.basic.client.SimplePanel"/>
  <component id="decoratorPanel" clientClass="br.com.sysmap.crux.basic.client.DecoratorPanel"/>
  <component id="focusPanel" clientClass="br.com.sysmap.crux.basic.client.FocusPanel"/>
  <component id="formPanel" clientClass="br.com.sysmap.crux.basic.client.FormPanel" clientConstructorParams="id, element"/>
  <component id="simpleLazyPanel" clientClass="br.com.sysmap.crux.basic.client.SimpleLazyPanel" />
  <component id="popupPanel" clientClass="br.com.sysmap.crux.basic.client.PopupPanel" clientConstructorParams="id, element"/>
  <component id="decoratedPopupPanel" clientClass="br.com.sysmap.crux.basic.client.DecoratedPopupPanel" clientConstructorParams="id, element"/>
  <component id="horizontalSplitPanel" clientClass="br.com.sysmap.crux.basic.client.HorizontalSplitPanel" clientConstructorParams="id, element"/>
  <component id="VerticalSplitPanel" clientClass="br.com.sysmap.crux.basic.client.VerticalSplitPanel" clientConstructorParams="id, element"/>
  <component id="scrollPanel" clientClass="br.com.sysmap.crux.core.client.component.ScrollPanel" />
  
  
  
  
  
  
  <component id="absolutePanel" 
  			 clientClass="br.com.sysmap.crux.core.client.component.Container"
             clientConstructorParams="id, new com.google.gwt.user.client.ui.AbsolutePanel()" />
  <component id="stackPanel" 
  			 clientClass="br.com.sysmap.crux.core.client.component.Container"
             clientConstructorParams="id, new com.google.gwt.user.client.ui.StackPanel()" />
  <component id="htmlPanel" 
  			 clientClass="br.com.sysmap.crux.basic.client.HTMLContainer"
             clientConstructorParams="id" />
</crux>
